DELETE  http://localhost:3000/usuarios/58c42229-d16b-4502-9580-6855cf28b3d4

###########################################

PUT http://localhost:3000/usuarios/58c42229-d16b-4502-9580-6855cf28b3d4
Content-Type: application/json

{
    "nome": "João Guilherme",
    "email": "joao@mail.com",
    "senha": "12365678"
}

###########################################

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "João",
    "email": "joao@mail.com",
    "senha": "12365678"
}

###########################################
GET http://localhost:3000/usuarios